name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Download and install .NET SDK 8.0.3
      run: |
        # Download .NET SDK 8.0.3 installer
        Invoke-WebRequest -Uri "https://download.visualstudio.microsoft.com/download/pr/6dd60d95-f5ae-414e-8259-b2a115e51714/c56f08471133d789dee9ffa52ddf5c1e/dotnet-sdk-8.0.300-win-x64.zip" -OutFile dotnet-sdk-installer.exe

        # Install .NET SDK 8.0.3
        Start-Process -FilePath dotnet-sdk-installer.exe -ArgumentList '/quiet /norestart' -Wait

        # Clean up installer
        Remove-Item -Path dotnet-sdk-installer.exe

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # Update to Node.js 20

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --configuration Release --logger trx

    # Generate coverage report
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.3.4
      with:
        reports: '**/*.trx'
        targetdir: coverage-report
        reporttypes: 'HtmlInline_AzurePipelines'

    # Upload coverage report as artifact
    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage-report
