name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Download and install .NET SDK 8.0.4
      run: |
        # Download .NET SDK 8.0.4 installer
        Invoke-WebRequest -Uri "https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-8.0.404-windows-x64-installer" -OutFile dotnet-sdk-installer.exe

        # Install .NET SDK 8.0.4
        Start-Process -FilePath dotnet-sdk-installer.exe -ArgumentList '/quiet /norestart' -Wait

        # Clean up installer
        Remove-Item -Path dotnet-sdk-installer.exe

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # Update to Node.js 20

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --configuration Release --logger trx

    # Generate coverage report
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.3.4
      with:
        reports: '**/*.trx'
        targetdir: coverage-report
        reporttypes: 'HtmlInline_AzurePipelines'

    # Upload coverage report as artifact
    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage-report
